CREATE TABLE IF NOT EXISTS users_events (
    id          INT AUTO_INCREMENT NOT NULL,
    user_id     INT NOT NULL,
    event_id     INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE ON UPDATE CASCADE
);